kind: pipeline
name: jenkins

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: ich777/jenkins
    username: ich777
    password:
      from_secret: docker_password
    tags: latest